apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: codegen-sep4-5
  janus-idp.io/tekton: codegen-sep4-5
  backstage.io/kubernetes-id: codegen-sep4-5
  backstage.io/kubernetes-namespace: codegen-sep-5 
  app.kubernetes.io/part-of: codegen-sep4-5
resources: 
- initialize-namespace.yaml
- deployment.yaml
- route.yaml
- service.yaml
- model-config.yaml
- rhoai/
